### ISSUE TITLE
new version of mail 16.0 is currently not supported

### ISSUE THREAD

**Issue by h-spiess** [scr34m/MailReceipt#13]
hey,

I've updated my mac to Monterey 12.3 today and with it Mail to Version 16.0 (3696.80.82.1.1).

Unfortunately, MailReceipt is not supported on this version yet. I'm not sure if it could be an easy fix.

Thanks and nice work :)

**Comment by scr34m** [comment]
I will update my system and after i could create new build, thanks for reporting.

**Comment by scr34m** [comment]
You can find under releases.
