### ISSUE TITLE
Installation failed for macOS Ventura (13.1) Mail 16.0 (3731.300.101.1.3)

### ISSUE THREAD

**Issue by kuppj00** [scr34m/MailReceipt#19]
When installing the MailReceipt.pkg I am getting The installation failed.
The older version for Ventura 13.0  install is OK, but not working anymore after the upgrade to Ventura 13.1.

**Comment by scr34m** [comment]
Can you test the Signature plugin too?
What is the exact error message, in the menu you can enable log window.

**Comment by kuppj00** [comment]
Where can I find the Signature plugin?

Errors from log:
Dec 23 11:44:42 Hans-iMac-M1 Installer[1536]: Failed to load specified background image
Dec 23 11:44:42 Hans-iMac-M1 Installer[1536]: Top component package (null) not found or understood: treat as unsigned
Dec 23 11:45:05 Hans-iMac-M1 installd[1278]: PackageKit: ----- Begin install -----
Dec 23 11:45:05 Hans-iMac-M1 installd[1278]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=110 "An error occurred while extracting files from the package “MailReceipt.pkg”." UserInfo={NSLocalizedDescription=An error occurred while extracting files from the package “MailReceipt.pkg”., NSURL=file://localhost/Users/hans_kuppers/Downloads/MailReceipt%20MacOS%2013.1/MailReceipt.pkg, PKInstallPackageIdentifier=hu.deeb.MailReceipt, NSUnderlyingError=0x1242285d0 {Error Domain=PKXARArchiveErrorDomain Code=101 "archive open failed" UserInfo={NSURL=file:///Users/hans_kuppers/Downloads/MailReceipt%20MacOS%2013.1/MailReceipt.pkg, NSFileOwnerAccountID=501, NSFileHFSTypeCode=0, NSFileSystemFileNumber=26183604, NSFileExtensionHidden=false, NSFileSystemNumber=16777231, NSFileSize=61609, NSFileGroupOwnerAccountID=20, NSFileHFSCreatorCode=0, NSFileOwnerAccountName=hans_kuppers, NSFilePosixPermissions=420, NSFileCreationDate=2022-12-22 20:35:48 +0000, NSFileType=NSFileTypeRegular, NSFileProtectionKey=NSFileProtectionCompleteUntilFirstUserAuthentication, NSFileGroupOwnerAccountName=staff, NSFileReferenceCount=1, NSFileModificationDate=2022-12-22 20:35:48 +0000, NSLocalizedDescription=archive open failed}}} {
	    NSLocalizedDescription = "An error occurred while extracting files from the package \U201cMailReceipt.pkg\U201d.";
	    NSURL = "file://localhost/Users/hans_kuppers/Downloads/MailReceipt%20MacOS%2013.1/MailReceipt.pkg";
	    NSUnderlyingError = "Error Domain=PKXARArchiveErrorDomain Code=101 \"archive open failed\" UserInfo={NSURL=file:///Users/hans_kuppers/Downloads/MailReceipt%20MacOS%2013.1/MailReceipt.pkg, NSFileOwnerAccountID=501, NSFileHFSTypeCode=0, NSFileSystemFileNumber=26183604, NSFileExtensionHidden=false, NSFileSystemNumber=16777231, NSFileSize=61609, NSFileGroupOwnerAccountID=20, NSFileHFSCreatorCode=0, NSFileOwnerAccountName=hans_kuppers, NSFilePosixPermissions=420, NSFileCreationDate=2022-12-22 20:35:48 +0000, NSFileType=NSFileTypeRegular, NSFileProtectionKey=NSFileProtectionC
Dec 23 11:45:06 Hans-iMac-M1 Installer[1536]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Dec 23 11:45:06 Hans-iMac-M1 Installer[1536]: Displaying 'Install Failed' UI.
Dec 23 11:45:06 Hans-iMac-M1 Installer[1536]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

Full log:
[Installer Log 23-Dec-2022.txt](https://github.com/scr34m/MailReceipt/files/10294430/Installer.Log.23-Dec-2022.txt)

**Comment by scr34m** [comment]
`Error Domain=PKXARArchiveErrorDomain Code=101 "archive open failed"` the file maybe damaged can you download again?

Here is the same error https://forums.macrumors.com/threads/install-with-pkg-file-failed.2367425/ take a look at this description https://forums.macrumors.com/threads/install-with-pkg-file-failed.2367425/post-31745379

**Comment by kuppj00** [comment]
New download same error

**Comment by scr34m** [comment]
Okay then see the comment, this issue is in your system permission not about the pkg itself.

**Comment by kuppj00** [comment]
moved the file to my iCloud and now install it ok and working great again
thanks

**Comment by scr34m** [comment]
great
