### ISSUE TITLE
Incompatible Plug-ins Disabled

### ISSUE THREAD

**Issue by mx2x** [scr34m/MailReceipt#2]
Contact the makers of these plug-ins for versions that are compatible with Mail 13.4.

**Comment by scr34m** [comment]
Plugin is compatible with 13.4 (3608.80.23.2.2) currently using it, do you downloaded 0.6.0 version from the front page link?

BTW maybe i need to create releases instead of the dropbox links.

**Comment by mx2x** [comment]
Yes I did but after the upgrade to Catalina 10.15.5 I got this error message and it is disappeared from the plugins and it is impossible to add it again ..

Thank you

**Comment by scr34m** [comment]
I'm still on Catalina 10.15.4 (19E287), OSX doesn't popup any update available notification i try to update the system and try to fix.

**Comment by mx2x** [comment]
Ok - thank you - since I use topgrade for periodic updates it seems I get all faster ...

**Comment by scr34m** [comment]
Upgraded the system, it seems a signing issue now investigating to resolve.

**Comment by scr34m** [comment]
With out codesign it's works soon will be available at the releases here in GH list.

**Comment by scr34m** [comment]
New file uploaded under releases

**Comment by mx2x** [comment]
Great ... after issuing: 

defaults write com.apple.mail EnableBundles -bool false
defaults write com.apple.mail EnableBundles -bool true 

I was able to reinstall it :-)

Thank you !!!!!
