### ISSUE TITLE
Support for Ventura 13.2

### ISSUE THREAD

**Issue by itxworks** [scr34m/MailReceipt#20]
Good Morning,

I hope you are doing well and find time to add Support for the latest Release.

Thank you.

**Comment by scr34m** [comment]
It's ready, you can download now, cya.

**Comment by ElleLuca** [comment]
Hi,  I just installed your plugin in my MacMail on OS Ventura.
The R & D buttons do appear.
First a question: To request either R or D, do they have to be "white" or "greyed"?

I assume "white" but I tested it both ways sending mail to myself on another account and have not received  but I not see any notifications. Where and how should I see them?

Thank you,
Luca

Additional info:
When I select R & D and I send I get an error message
"Cannot send message using the server XXX" (none of my servers work).

"Verify that you have addressed this message correctly. Check your SMTP server settings in Mail preferences and verify any advanced settings with your system administrator.

The server response was: <[luca2@rendertech.com](mailto:luca2@rendertech.com)> NOTIFY=SUCCESS,FAILURE: malformed address:

**Comment by scr34m** [comment]
The buttons should be white to be active.

Not so many server supports delivery notifications, with postfix it works.
And client applications like outlook supports reading notifications and webmail roundcube too i tested them maybe thunderbird too.

If the server responds error back then it is not Postfix and / or not supporting NOTIFY parameter.
