### ISSUE TITLE
Installation and its safety

### ISSUE THREAD

**Issue by RoHe56** [scr34m/MailReceipt#22]
Hello,
I apologize for my suspiciousness, but I want to make sure that MailReceipt is not sending or somehow abusing the sent emails. 
When installing the Plug-in into the Mail client, the OS warns me: "_The Plug-in will gain access to accounts, messages, files, folders and attachments stored on your computer. If it comes from an unknown developer or you do not trust the developer, do not allow access_".

Once again, I apologize for my caution.
Thank you Roman

**Comment by scr34m** [comment]
This is a normal notice from Apple, but of course my plugin not doing any harmful thing, but the source code is open so everyone can build them for your selfs if not accepting my builds.

**Comment by RoHe56** [comment]
OK, thanks. I've already installed it.
