### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by m-graf** [scr34m/MailReceipt#4]
Hey there, this is open-end. I understand the concepts you're implementing, but what does a green path look like? Should I receive a notification if the receivers client respects the headers you're looking for? Do notifications come from the Notification Center, or from a mail message?

Thanks for this. As I understand it, developing these plugins is difficult because Apple doesn't publicly document the API.

Thanks again

**Comment by scr34m** [comment]
There are two notification:
- one is sent back the server if supports the function and if it was able to deliver the e-mail to the mail box this is button D
- other one only sent if recipient reads the e-mail and the e-mail client supports is, recipient can decide to response No and no report will be sent by e-mail this is button R

Both reports are e-mail and you receive e-mail.

**Comment by tmimy** [comment]
I have install and use the plugin although my IMAP server supports tracking (I tried sing outlook- win 10) but unfortunately I got an error her in Mac after doing all steps

**Comment by tmimy** [comment]
![image](https://user-images.githubusercontent.com/52251660/114265477-b1926580-99f9-11eb-9d94-b1695418187c.png)

**Comment by tmimy** [comment]
> I have install and use the plugin although my IMAP server supports tracking (I tried sing outlook- win 10) but unfortunately I got an error her in Mac after doing all steps

![image](https://user-images.githubusercontent.com/52251660/114266127-3df25780-99fd-11eb-81e6-eebfaeaf6bd7.png)

**Comment by scr34m** [comment]
What kind of server software used? I've using / tested with postfix and it's working on that.
You can see the welcome response if connect from console on 465 / 25 port.

**Comment by tmimy** [comment]
> What kind of server software used? I've using / tested with postfix and it's working on that.
> You can see the welcome response if connect from console on 465 / 25 port.

As mentioned on READ.ME I used iOS mail

**Comment by scr34m** [comment]
I'm asking about SMTP server software, not the client software, because only of course i is Mail.app

**Comment by tmimy** [comment]
I am using Goddady cP webmail then inside I have two options : horde software or roundcube software 
both are not working

**Comment by scr34m** [comment]
Thos options only for accessing e-mails that you already received, if you can give me the SMTP address then i can try to check which software is used. This plugin sends a command to SMTP server to ask SMTP server to generate response if e-mail was delivered and recipient server supports this notification.

**Comment by tmimy** [comment]
sg2plcpnl0140.prod.sin2.secureserver.net

**Comment by tmimy** [comment]
mail.alhathlul.com
SMTP Port: 587
non-ssl

**Comment by scr34m** [comment]
This is an exim SMTP server:
```
220-sg2plcpnl0140.prod.sin2.secureserver.net ESMTP Exim 4.93 #2 Sat, 10 Apr 2021 09:40:43 -0700
220-We do not authorize the use of this system to transport unsolicited,
220 and/or bulk e-mail.
```

i will check this server and will write back.

**Comment by scr34m** [comment]
What is NOTIFY talked about here: https://www.lifewire.com/what-is-dsn-delivery-status-notification-for-smtp-email-3860942
Postfix supports http://www.postfix.org/DSN_README.html

With tests i've received the same error message on docker exim server, but i didn't found any solution how to communicate with exim servers.

**Comment by tmimy** [comment]
Thanks appreciate your help
