### ISSUE TITLE
FEATURE REQUEST - New Mail extension for 'Disable Mark as Read'

### ISSUE THREAD

**Issue by gspannu** [scr34m/MailReceipt#8]
**FEATURE REQUEST**

Could you develop a small mail extension to prevent macOS Mail from marking a mail message as Read as soon as the message is selected?

This extension should prevent the mail message to be _marked as read_ until the message has been _opened_ specifically (double-clicking) or marked as read _manually_. 

This feature exists in all mail clients like MS Outlook but has been missing from macOS Mail.

Do you think you could build a mail extension for this feature please? Maybe use the new mail extension framework availbale in macOS Monterey?

Thanks.
Guru

**Comment by scr34m** [comment]
I'll check what can i do, but every release (including debug, testing) need to be notarized otherwise the Mail.app not loads it which is a pity and very hard to develop.

Do you have any source for this Monterey mail extension framework didn't hear about it.

**Comment by scr34m** [comment]
I've found this https://developer.apple.com/videos/play/wwdc2021/10168/ on firest search you think about this?

**Comment by gspannu** [comment]
**Yes, you are correct.** 
macOS Monterey (still in Beta) has a new framework for mail extensions - that has why I mentioned it.

Your _link_ above is the correct one. 

I am also **attaching the resource example** of the same link from Apple WWDC video. 

[BuildMailAppExtensions.zip](https://github.com/scr34m/MailReceipt/files/6768247/BuildMailAppExtensions.zip)

**Comment by scr34m** [comment]
Well it looks like more restrictive about the video presentation instead what we can do now, but as they said plugins will be discontinued.

**Comment by gspannu** [comment]
Hi,

Just checking .... Any progress or update on the simple mail extension to 'not mark mail as read' automatically?
Thanks.

**Comment by scr34m** [comment]
Just checked the documentations about this and so fare looks not possible, but after a second beta release i'll download and try in a VM, in the up comping weeks.

**Comment by scr34m** [comment]
I've checked, there is not chance to work with this.
But the plugins are still working on the latest Monterey Beta 6 release in Mail.app

**Comment by gspannu** [comment]
> I've checked, there is not chance to work with this.
> But the plugins are still working on the latest Monterey Beta 6 release in Mail.app

Thank you...

**Comment by scr34m** [comment]
BTW i will check the possibilities to create a plugin for you

**Comment by scr34m** [comment]
I could identify two methods which is called when a message selected / opened or when changing read/unread from context menu.

Because these functions called by some inner function which is not named i can relay only on checking call stack to determine it was marked readed from context menu.

Do you still need this kind of plugin?

**Comment by gspannu** [comment]
> I could identify two methods which is called when a message selected / opened or when changing read/unread from context menu.
> 
> Because these functions called by some inner function which is not named i can relay only on checking call stack to determine it was marked readed from context menu.
> 
> Do you still need this kind of plugin?

Yes, please…. I still need this plugin. 
I love macOS Mail but this feature is the only reason I have to keep using MS Outlook instead. 
This plugin will be a great help…. Thanks.

**Comment by scr34m** [comment]
You can download and check https://github.com/scr34m/MailDisableAutoRead/releases/tag/v0.1.0 if any question then please create a ticket there.

**Comment by gspannu** [comment]
> You can download and check https://github.com/scr34m/MailDisableAutoRead/releases/tag/v0.1.0 if any question then please create a ticket there.

Thank you. I am away for about a week, but will download, use and check and report back as soon as I am back home. Thank you, once again for your efforts. 👍
